### PR TITLE
Add tools for docking with Autodock Vina

### PR DESCRIPTION
**Pull request by leobiscassi**
Modifications performerd according with trello card [1]

[1] https://trello.com/c/RCZHzFkt

### CODE REVIEW

**Comment by adefelicibus** [comment]
Hi @leobiscassi , in my implementation, Galaxy does not recognize the MOL2 type automatically in the upload tool. Have you tested it in your environment?
Apparently, the MOL2 class is correctly defined in the molFiles.py file.
The Autodock Vina tools worked well.

**Comment by rodrigofaccioli** [comment]
Great work @leobiscassi and @adefelicibus !!!
Please, tell me when this tool is able to run. I would like to perform some docking.

**Comment by leobiscassi** [comment]
Hi @adefelicibus , yes, works fine in my development environment, see attachment.

alexandre

Next, my code in local environment:

**datatypes_config.xml**

``` xml
<datatype extension="mol2" type="galaxy.datatypes.molFiles:MOL2" display_in_upload="true" />
```

**molFiles.py**

``` python
class MOL2(GenericMultiMolFile):
    file_ext = "mol2"

    def sniff(self, filename):
        self.no_mols = commands.getstatusoutput("grep -c @\<TRIPOS\>MOLECULE "+filename)
        if (self.no_mols[0] == 0) & (self.no_mols[1] > 0):
            return True
        else:
            return False
```

**Comment by adefelicibus** [comment]
Ok @leobiscassi, this is correct.
But, I said that when you upload a MOL2 file with auto-detect, Galaxy doesn't recognize the type.
Maybe the problem is on the sniff function.

**Comment by leobiscassi** [comment]
@adefelicibus I'll revise this function, thanks.

**Pull request merged**
